---
- hosts: all
  user: vagrant
  gather_facts: False
  sudo: yes
  vars:
    - root_dir: /home/vagrant
    - habit_repo: https://github.com/edthedev/habitrpg.git
    - app_root: "{{ root_dir }}/habitrpg"
  tasks:
    - name: apt-add-repository
      apt: name={{ item }}
      with_items:
        - python-software-properties
        - python
        - g++
        - make
    - name: latest node
      apt_repository: state=present repo="deb http://ppa.launchpad.net/chris-lea/node.js/ubuntu precise main" 
    - name: unsuck apt
      shell: apt-get update
    - name: required
      apt: name={{ item }}
      with_items:
        - git-core
        - libssl-dev
        - nodejs
        - npm
    - name: clone
      git: repo={{ habit_repo }} dest={{ app_root }} update=no accept_hostkey=True
    - name: grunt
      npm: name={{ item }} global=yes
      sudo: yes
      with_items: 
        - grunt-cli
        - bower
    - name: deps
      npm: path={{ app_root }}
