---
- hosts: all
  user: vagrant
  gather_facts: False
  sudo: yes
  vars:
    - root_dir: /home/vagrant
    - habit_repo: git@github.com:edthedev/habitrpg.git
    - app_root: "{{ root_dir }}/habitrpg"
  tasks:
    - name: system
      apt: name={{ item }}
      with_items:
        - git-core
    - include: node.yml
    - name: clone
      git: repo={{ habit_repo }} dest={{ root_dir }}
    - name: grunt
      npm: name={{ item }} global=yes
      sudo: yes
      with_items: 
        - grunt-cli
        - bower
    - name: deps
      npm: path={{ app_root }}
